name: UnitTest Ubuntu

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit_test_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Install dependecies
        run: |
            sudo apt-get update
            sudo apt install g++ -y
            sudo apt install cmake -y
            sudo apt-get install build-essential -y
            sudo apt install libgtest-dev -y
            sudo apt install libboost-program-options-dev -y
            sudo apt-get install libssl-dev -y
            sudo apt-get install ca-certificates -y
            sudo apt-get install libpoco-dev -y
            sudo apt-get install libpoconetssl80 -y
            sudo apt-get install libmysqlclient-dev -y
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build project
        run: |
          cmake .
          cmake --build . --config Release
      - name: Test project
        run: ctest

